

all:
	gcc -O2 -fPIC -shared -Dpython3 -Wl,-Bsymbolic-functions -I/usr/include/python2.7 -o hello.so example1.c

python3:
	gcc -O2 -fPIC -shared -Dpython3 -Wl,-Bsymbolic-functions -I/usr/include/python2.7 -o hello.so example1.c
